# Generated by Django 4.0.4 on 2022-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('username', models.CharField(default='username', max_length=20)),
                ('identify', models.CharField(default='identify', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
    ]
